Humi-HR/taxman

.github/SECURITY.md, .github/dependabot.yml, README.md
Now that this repo is public, we should put these back.
=> changes for the public facing repo

lib/taxman.rb, lib/taxman/taxman2023/module_mapper.rb, spec/taxman/taxman2023/module_mapper_spec.rb
Just starting out with some better logging of errors. Let me know if there's other areas you see that needs improvement.
=> feat: Raise error on unsupported province

Gemfile.lock, lib/taxman/version.rb
Looks like the release PR didn't get created automatically - maybe having `bug:bug-8143` in the commit message confused it?
=> Bump version number

lib/taxman/taxman2023/mb/t4.rb, spec/integration/taxman2023/bug_8143_spec.rb, spec/integration/taxman2023/test24_spec.rb
https://gethumi.atlassian.net/browse/PAY-852
effective July 1 2023 19,145 TD1 basic exemption
test 24 changes
[Employee name-(EE)-PDOC-Date paid-2023-07-15.pdf](https://github.com/Humi-HR/taxman/files/11984155/Employee.name-.EE.-PDOC-Date.paid-2023-07-15.pdf)
bug 8143 spec changes
[PDOC.8143.pdf](https://github.com/Humi-HR/taxman/files/12029784/PDOC.8143.pdf)
=> fix: New prorated personal exemption MB

lib/taxman/taxman2023/bonus_tax_calculator.rb
Reference: https://gethumi.atlassian.net/browse/PAY-961
Since the ticket is not high priority, I will wait for a review on this one from Greg since it's diverting from T4127.
=> fix: Ensure bonus taxes cannot be negative

lib/taxman/taxman2023/qpp_input.rb, spec/taxman/taxman2023/qpp_input_spec.rb
QPP basic inputs.
https://gethumi.atlassian.net/browse/PAY-915
=> feat: Add basic inputs for QPP calculations

lib/taxman/taxman2023/qpip_input.rb, spec/taxman/taxman2023/qpip_input_spec.rb
Basic QPIP input adapter
https://gethumi.atlassian.net/browse/PAY-916
=> feat: Add input adapter for calculating QPIP

lib/taxman/taxman2023/calculate.rb, lib/taxman/taxman2023/qc_ap.rb, lib/taxman/taxman2023/qc_ap1.rb, lib/taxman/taxman2023/qpip/constants.rb, lib/taxman/taxman2023/qpip_calculator.rb, lib/taxman/taxman2023/qpip_input.rb, spec/taxman/taxman2023/calculate_spec.rb, spec/taxman/taxman2023/qc_ap1_spec.rb, spec/taxman/taxman2023/qc_ap_spec.rb, spec/taxman/taxman2023/qpip_calculator_spec.rb, spec/taxman/taxman2023/qpip_input_spec.rb
https://gethumi.atlassian.net/browse/PAY-918
Implements QPIP calculation and fixes input parser to include s7.
=> feat: Add support for calculating QPIP

lib/taxman/taxman2023/calculate.rb, lib/taxman/taxman2023/f5_a.rb, lib/taxman/taxman2023/f5_b.rb, lib/taxman/taxman2023/f5_q.rb, spec/taxman/taxman2023/f5_a_spec.rb, spec/taxman/taxman2023/f5_b_spec.rb, spec/taxman/taxman2023/f5_q_spec.rb
https://gethumi.atlassian.net/browse/PAY-919
=> [PAY-919] implement f5q calculation and update f5a and f5b

lib/taxman/taxman2023/bonus_tax_calculator.rb, spec/taxman/taxman2023/bonus_tax_calculator_spec.rb
https://gethumi.atlassian.net/browse/PAY-924
=> feat: Set flag tax for bonuses in Quebec

lib/taxman/taxman2023/t.rb, spec/taxman/taxman2023/t_spec.rb
https://gethumi.atlassian.net/browse/PAY-1081
=> Pay 1081 t 4127 support quebec in calculation of t

lib/taxman/taxman2023/factor.rb, lib/taxman/taxman2023/period_input.rb, lib/taxman/taxman2023/qc_cs.rb, lib/taxman/taxman2023/qc_csa.rb, lib/taxman/taxman2023/qc_h.rb, lib/taxman/taxman2023/qc_i.rb, lib/taxman/taxman2023/tax_calculator.rb, spec/taxman/taxman2023/period_input_spec.rb, spec/taxman/taxman2023/qc_cs_spec.rb, spec/taxman/taxman2023/qc_csa_spec.rb, spec/taxman/taxman2023/qc_h_spec.rb, spec/taxman/taxman2023/qc_i_spec.rb
https://gethumi.atlassian.net/browse/PAY-928?atlOrigin=eyJpIjoiMjFkMWY0YTIwMjMzNDgyNmFkMzNhYTc4OTQ2ZWZhN2UiLCJwIjoiaiJ9
squashed version of #75
=> Pay 928 calculate QcI

lib/taxman/taxman2023/qc_d1.rb, lib/taxman/taxman2023/qc_h2.rb, lib/taxman/taxman2023/year_input.rb, spec/taxman/taxman2023/qc_d1_spec.rb, spec/taxman/taxman2023/qc_h2_spec.rb, spec/taxman/taxman2023/year_input_spec.rb
This value will later be used in bonus tax calculation.
Reference: https://gethumi.atlassian.net/browse/PAY-936
=> feat: Add calculation for QC H2

lib/taxman/taxman2023/personal_tax_deductions_input.rb, lib/taxman/taxman2023/qc_e.rb, lib/taxman/taxman2023/qc_y.rb, lib/taxman/taxman2023/tax_calculator.rb, spec/taxman/taxman2023/personal_tax_deductions_input_spec.rb, spec/taxman/taxman2023/qc_e_spec.rb, spec/taxman/taxman2023/qc_y_spec.rb
https://gethumi.atlassian.net/browse/PAY-931?atlOrigin=eyJpIjoiNmQ5NWY0NTU3ZjI4NGI4ZDgwN2VmYjlhYTI1NzdkNjAiLCJwIjoiaiJ9
=> feat: calculate quebec income tax for the year (Y)

lib/taxman/taxman2023/bonus_tax_calculator.rb, lib/taxman/taxman2023/tax_calculator.rb
https://gethumi.atlassian.net/browse/PAY-941
=> feat: Add switches between QC and non-QC

lib/taxman/taxman2023/qc_i1.rb, lib/taxman/taxman2023/year_input.rb, spec/taxman/taxman2023/qc_i1_spec.rb, spec/taxman/taxman2023/year_input_spec.rb
https://gethumi.atlassian.net/browse/PAY-935
=> Pay 935 tp 1015 f expand upon existing i to calculate annual taxable income on bonus payments i 1 or implement new i 1 class

lib/taxman/taxman2023/qc_csb.rb, lib/taxman/taxman2023/qc_y1_y2.rb, lib/taxman/taxman2023/year_input.rb, spec/taxman/taxman2023/qc_csb_spec.rb, spec/taxman/taxman2023/qc_y1_y2_spec.rb, spec/taxman/taxman2023/year_input_spec.rb
Reference: https://gethumi.atlassian.net/browse/PAY-938
=> feat: Implement Y1 and Y2 calculations for bonus

lib/taxman/taxman2023/qc_a.rb, lib/taxman/taxman2023/qc_h.rb, lib/taxman/taxman2023/tax_calculator.rb, spec/taxman/taxman2023/qc_a_spec.rb, spec/taxman/taxman2023/qc_h_spec.rb, spec/taxman/taxman2023/tax_calculator_spec.rb
https://gethumi.atlassian.net/browse/PAY-934?atlOrigin=eyJpIjoiY2Q4NTJhNjhkMTI5NGQ5ZWI5NmU0OGVmZjNhYjQ4MzEiLCJwIjoiaiJ9
=> pay 934 calculate quebec income tax to be withheld for the pay period

lib/taxman/taxman2023/bonus_tax_calculator.rb, lib/taxman/taxman2023/qc_a1.rb, spec/taxman/taxman2023/qc_a1_spec.rb
Note that flat 7% tax for small pay was implemented earlier.
Reference: https://gethumi.atlassian.net/browse/PAY-939
=> feat: Add bonus taxes for Quebec

.rubocop.yml, lib/taxman/taxman2023.rb, lib/taxman/taxman2023/a.rb, lib/taxman/taxman2023/c.rb, lib/taxman/taxman2023/calculate.rb, lib/taxman/taxman2023/current_bonus_term.rb, lib/taxman/taxman2023/ei.rb, lib/taxman/taxman2023/f5.rb, lib/taxman/taxman2023/f5_a.rb, lib/taxman/taxman2023/f5_b.rb, lib/taxman/taxman2023/f5_q.rb, lib/taxman/taxman2023/factor.rb, lib/taxman/taxman2023/k2_generic.rb, lib/taxman/taxman2023/qc_ap.rb, lib/taxman/taxman2023/qc_ap1.rb, lib/taxman/taxman2023/qc_c.rb, lib/taxman/taxman2023/t.rb, lib/taxman/taxman2023/t1.rb, lib/taxman/taxman2023/t2_generic.rb, lib/taxman/taxman2023/t3.rb, lib/taxman/taxman2023/t4_generic.rb, lib/taxman/taxman2023/tax_calculator.rb, lib/taxman/taxman2023/ytd_bonus_term.rb
follow-up to https://github.com/Humi-HR/taxman/pull/75/files#discussion_r1307915904
#75 introduced a base class for tax factors; let's use it whereever we can
=> use Factor base class

lib/taxman/taxman2023/period_input.rb, spec/taxman/taxman2023/period_input_spec.rb
https://gethumi.atlassian.net/browse/PAY-921
=> [PAY-921] Inputs for transfer between cpp qpp

lib/taxman/taxman2023/t3.rb, lib/taxman/taxman2023/tax_calculator.rb, spec/integration/taxman2023/pay_4440_spec.rb, spec/taxman/taxman2023/bonus_tax_calculator_spec.rb, spec/taxman/taxman2023/t3_spec.rb, spec/taxman/taxman2023/tax_calculator_spec.rb
https://gethumi.atlassian.net/browse/PAY-922
=> [PAY-922] use correct k2 values in t3

lib/taxman/taxman2023/qpip_calculator.rb, spec/integration/taxman2023/qc_spreadsheet_spec.rb, spec/integration/taxman2023/qc_test4_spec.rb
Implement QC test case 4 and CRA 28
=> Pay 1219 implement test case 4

lib/taxman/taxman2023/qpp_calculator.rb, spec/integration/taxman2023/qc_spreadsheet_spec.rb, spec/integration/taxman2023/qc_test1_spec.rb
=> Pay 1216 implement test case 1

spec/integration/taxman2023/test_case_2_spec.rb
https://gethumi.atlassian.net/browse/PAY-1217
=> [PAY-1217] feat: implement test case 2

README.md
Mostly here to trigger a major version upgrade
=> feat!: Add Quebec support

lib/taxman/taxman2023/pension_input.rb, lib/taxman/taxman2023/period_input.rb, spec/integration/taxman2023/qc_spreadsheet_spec.rb, spec/integration/taxman2023/qc_test1_spec.rb, spec/integration/taxman2023/qc_test4_spec.rb, spec/integration/taxman2023/test_case_2_spec.rb, spec/taxman/taxman2023/pension_input_spec.rb, spec/taxman/taxman2023/period_input_spec.rb
- feat: Split out QC inputs for pension
- feat: Split out QC period input
=> PAY 1350 taxman split out inputs for qc and cra for taxable and pensionable

lib/taxman/taxman2024/c2.rb, lib/taxman/taxman2024/calculate.rb, lib/taxman/taxman2024/cpp/constants.rb, lib/taxman/taxman2024/cpp_calculator.rb, lib/taxman/taxman2024/k2_p_generic.rb, lib/taxman/taxman2024/pension_input.rb, lib/taxman/taxman2024/w.rb, spec/taxman/taxman2024/c2_spec.rb, spec/taxman/taxman2024/cpp/constants_spec.rb, spec/taxman/taxman2024/cpp_calculator_spec.rb, spec/taxman/taxman2024/f5_spec.rb
updates constants and implements cpp second additional contribution
https://gethumi.atlassian.net/browse/PAY-1414
=> PAY-1414 CPP updates

lib/taxman/taxman2024/ab/t4.rb, lib/taxman/taxman2024/bc/t4.rb, lib/taxman/taxman2024/ei.rb, lib/taxman/taxman2024/mb/t4.rb, lib/taxman/taxman2024/nb/t4.rb, lib/taxman/taxman2024/nl/t4.rb, lib/taxman/taxman2024/nt/t4.rb, lib/taxman/taxman2024/nu/t4.rb, lib/taxman/taxman2024/on/t4.rb, lib/taxman/taxman2024/pe/t4.rb, lib/taxman/taxman2024/qpip/constants.rb, lib/taxman/taxman2024/qpp/constants.rb, lib/taxman/taxman2024/sk/t4.rb, lib/taxman/taxman2024/t3.rb, lib/taxman/taxman2024/yt/t4.rb
updated rates and constants for federal and provincial tax, EI, QPP and QPIP
https://gethumi.atlassian.net/browse/PAY-1411 also https://gethumi.atlassian.net/browse/PAY-1412
https://www.canada.ca/en/revenue-agency/services/forms-publications/payroll/t4127-payroll-deductions-formulas/t4127-jan/t4127-jan-payroll-deductions-formulas-computer-programs.html#toc77 table 8.2, 8.3, 8.7 and 8.8
=> PAY-1411 2024 rates and constants

lib/taxman/taxman2024/calculate.rb, spec/taxman/taxman2024/calculate_spec.rb, spec/taxman/taxman2024/ei_spec.rb, spec/taxman/taxman2024/k2_q_spec.rb, spec/taxman/taxman2024/pension_input_spec.rb, spec/taxman/taxman2024/yt/t4_spec.rb
https://gethumi.atlassian.net/browse/PAY-1453
fixes the more unit-testy of the failing rspecs; integration tests will be fixed later once all the 2024 changes are in
=> PAY-1453 fix unit tests

lib/taxman/taxman2024/ei.rb, lib/taxman/taxman2024/f5_q.rb, lib/taxman/taxman2024/qpp/constants.rb, spec/taxman/taxman2024/f5_q_spec.rb
QC constant updates and include C2 in F5Q
per https://www.notion.so/humi/Update-Federal-Quebec-Tax-Calculations-805ae73a73f545e5a7a5c787b95efdf1?pvs=4#1791f0a1bf224935901fbffa0c3f4d24
https://gethumi.atlassian.net/browse/PAY-1487
=> PAY-1487 more QC updates

lib/taxman/taxman2024/bpaf.rb, spec/taxman/taxman2024/bpaf_spec.rb
https://gethumi.atlassian.net/browse/PAY-1488
=> PAY-1488 update BPAF for 2024

lib/taxman/taxman2024/bc/t2.rb, lib/taxman/taxman2024/on/t2.rb, lib/taxman/taxman2024/pe/t2.rb, spec/taxman/taxman2024/bc/t2_spec.rb, spec/taxman/taxman2024/pe/t2_spec.rb
update provincial S and V1 calculations
https://gethumi.atlassian.net/browse/PAY-1491
=> PAY-1491 update province-specific calculations

lib/taxman.rb, lib/taxman/taxman2024/calculate.rb, spec/taxman/taxman2024/calculate_spec.rb
it's possible to pass the wrong year's inputs into the calculation... let's fix that
=> fix: check that correct year's input are being used

lib/taxman/taxman2024/cpp_calculator.rb, lib/taxman/taxman2024/qpp_calculator.rb, spec/integration/taxman2024/test17_spec.rb, spec/integration/taxman2024/test8_spec.rb, spec/taxman/taxman2024/cpp_calculator_spec.rb, spec/taxman/taxman2024/qpp_calculator_spec.rb
https://gethumi.atlassian.net/browse/PAY-1559
=> PAY-1559: report CPP2 separately from CPP

.github/workflows/release-please.yml
This reverts commit fbb2091cf30ef336d4d579074324aac93d49faf3.
=> Revert "chore(deps): bump google-github-actions/release-please-action"

lib/taxman/taxman2024/qc_y.rb, spec/taxman/taxman2024/qc_y1_y2_spec.rb, spec/taxman/taxman2024/qc_y_spec.rb, spec/taxman/taxman2024/tax_calculator_spec.rb
https://gethumi.atlassian.net/browse/PAY-1602
rspec expected values are from greg's qc spreadsheet w/ 2024 rates and constants
=> PAY-1602 feat: update QC tax rates and constants for 2024

lib/taxman/taxman2024/qc_h.rb, spec/taxman/taxman2024/qc_h2_spec.rb, spec/taxman/taxman2024/qc_h_spec.rb, spec/taxman/taxman2024/tax_calculator_spec.rb
https://gethumi.atlassian.net/browse/PAY-1610
per https://www.revenuquebec.ca/documents/en/formulaires/tp/TP-1015.F-V%282024-01%29.pdf
=> PAY-1610 update QC maximum deduction for employment income for 2024

.github/workflows/release-please.yml, .release-please-manifest.json, release-please-config.json
Take two on bootstrapping this manually
https://github.com/googleapis/release-please/blob/main/docs/manifest-releaser.md#quick-start
=> Take 2 on release please v4

release-please-config.json
Need to set a SHA for the new version of release-please to know where to start
counting from.
=> Set last release SHA

release-please-config.json
Aooarently this needs to be set in the root of the config.
=> Set bootstrap sha in root

spec/integration/taxman2024/qc_test1_spec.rb, spec/integration/taxman2024/qc_test2_spec.rb, spec/integration/taxman2024/qc_test3_spec.rb, spec/integration/taxman2024/qc_test4_spec.rb
https://gethumi.atlassian.net/browse/PAY-1603
* add new PensionInput parameters to 2024 QC tests
* fix the filenames
=> PAY-1603 prep for qc integration tests

lib/taxman.rb, lib/taxman/taxman2018.rb, lib/taxman/taxman2018/cpp.rb, lib/taxman/taxman2018/ei.rb, lib/taxman/taxman2019.rb, lib/taxman/taxman2019/cpp.rb, lib/taxman/taxman2019/ei.rb, lib/taxman/taxman2020.rb, lib/taxman/taxman2020/cpp.rb, lib/taxman/taxman2020/ei.rb
Adding old constants for use by importer.
=> Add old constants for CPP and EI
